# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

name: CI-CD

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: CI
    displayName: 'CI - Pipeline de CI'
    jobs:
    - job: BuildAndTest
      displayName: 'Executando build do projeto'
      steps:
      - task: DotNetCoreCLI@2
        inputs:
          command: 'build'
          projects: './src/Review-Filmes.sln'
      - task: DotNetCoreCLI@2
        inputs:
          command: 'test'
          projects: './src/Review-Filmes.Test.Unit/Review-Filmes.Test.Unit.csproj'

