# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

name: CI-CD

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: CI
    displayName: 'CI - Pipeline de CI'
    jobs:
    - job: BuildAndTest
      displayName: 'Executando build do projeto'
      steps:
      - task: DotNetCoreCLI@2
        displayName: Build
        inputs:
          command: 'build'
          projects: './src/Review-Filmes.sln'
          
      - task: CmdLine@2
        inputs:
          script: 'ls ./src/'

      - task: DotNetCoreCLI@2
        displayName: Test
        inputs:
          command: 'test'
          projects: './src/Review-Filmes.Test.Unit/Review-Filmes.Test.Unit.csproj'
    
    #criar nova versão do app
    - job: Release
      displayName: 'Release'
      dependsOn: BuildAndTest
      steps:
      - task: DotNetCoreCLI@2
        inputs:
          azureSubscription: 'Azure subscription 1(5a2e81d1-1ba9-446a-87eb-fa6fe75eca50)'
          command: 'publish'
          publishWebProjects: true

      #enviando para web app
      - task: AzureWebApp@1
        inputs:
          azureSubscription: 'Azure subscription 1(5a2e81d1-1ba9-446a-87eb-fa6fe75eca50)'
          appType: 'webAppLinux'
          appName: 'lab-web-app01'
          package: '$(System.DefaultWorkingDirectory)/**/*.zip'
