# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

name: CI-CD

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: CI
    jobs:
      - job: Build
        displayName: "Docker Build and Push"
        steps:
          - template: ./templates/ci-docker-build-push.yml
            parameters:
            #set parameters pipeline variables
              imageRepository: $(imageRepository)    #'exemploapprepo'
              dockerfilePath: $(dockerfilePath)      #src/exemplo.app.Web/Dockerfile'
              tag: $(Build.BuildId)
              buildContext: $(buildContext)          #'src'
              containerRegistry: 'DockerHub'

  - stage: CD
    jobs:
      - job: Deploy
        displayName: "Deploy WebApp for Containes"
        steps:
          - template: ./templates/cd-web-app-containes.yml
            parameters:
            #set parameters pipeline variables
              WebAppName: $(WebAppName) 
              containerRegistry: $(containerRegistry)
              imageRepository: $(imageRepository)
              imageTag: $(imageTag)

